export enum projectType {
  game = 'game',
  tool = 'tool',
  developers = 'Developers',
  other = 'other',
  nft = 'NFT',
  defi = 'DEFI',
  DAO = 'DAO',
  dapp = 'dapp',
  exchange = 'Exchanges (DEX)',
  identity = 'Identity',
  community = 'Community',
  gaming = 'Gaming',
  insurance = 'Insurance',
  corporateBaker = 'Corporate Baker',
}
